version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/agents-grand-stack"
    schedule:
      interval: "yearly"

  - package-ecosystem: "npm"
    directory: "/agents-apollo-server"
    schedule:
      interval: "yearly"
