version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/agents-grand-stack"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/agents-apollo-server"
    schedule:
      interval: "daily"
